### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aspino** [learningtapestry/lcms-engine#3]
## 1st phase: Code extraction
- [x] Extract models
- [x] Extract migrations
- [x] Extract entities
- [x] Extract controllers
- [x] Extract interactors
- [x] Extract form objects
- [x] Extract helpers
- [x] Extract services
- [x] Extract jobs
- [x] Extract query objects
- [x] Extract rake tasks
- [x] Extract libraries
- [x] Extract uploaders
- [x] Extract serializers
- [x] Extract presenters
- [x] Extract views
- [x] Extract exceptions
- [x] Extract assets
- [x] Extract routes
- [x] Extract specs (#31)
- [x] Extract locales
- [x] Document extraction process and set up guidelines for the current client project maintainers

## 2nd phase: Refactoring & feature implementation
- [ ] Move all javascript assets, and perhaps also other types, to npm packages
- [x] Namespace all classes & assets belonging to the engine
- [x] Namespace all migrations
- [x] Clean up/refactor code to comply with rubocop rules
- [x] Implement basic/default features not tied to the client projects. The overall idea is that the engine must provide a fully functional core that clients can use as-is or extend if they prefer (#13)
- [x] Apply [semantic versioning](https://semver.org/), so that client projects can rely on specific versions to ensure compatibility (extracted to #16)
- [x] OCX implementation (extracted to #108)

**Comment by paranoicsan** [comment]
@aspino do you recall what was the intention to make
> Move all javascript assets, and perhaps also other types, to npm packages

I was sure we good to go with base assets included in the engine itself.

**Comment by aspino** [comment]
The motives were presented/discussed here: https://github.com/learningtapestry/lcms-engine/issues/1. Basically engines have no proper support for webpack, or at least they didn't when we last checked, so the options are either resorting to some kind of workaround to make it work, or switching to NPM packages for the assets. From what we could grasp from the Rails issue that is mentioned and other sources online, our impression was that the trend in the community was moving everything to NPM packages and not bother with webpack on engines, so that's why RM and I preferred this approach.

Things may have changed or improved by now, so perhaps there's a better alternative.

**Comment by paranoicsan** [comment]
Specs have been extracted (#31)

**Comment by shlag3n** [comment]
Some thoughts re assets, bc most of assets that we have here are legacy from unbounded and we didn't use them at other lcms projects except admin part.
1. All lcms projects share some basic admin panel and it's rather primitive - only few interactive elements are in use: curriculum tree + showing batch regeneration. Differences are in top menu/styles/some views and controllers and looks like in-built assets may work here, at least at first. 
2. User part is very different from project to project. If we need some simple base ui here we can create it as npm package, but we don't need to move ub assets to npm package because more likely functionality will be different from project to project. We used zero lines of user front-end ub part at other projects for now. 
3. We need to add API to engine that will include jwt based authorization, some basic curriculum queries etc. All projects will use it to build client specific ui.

If to include assets to the engine (again this make sense only for admin panel):
1. We need to think if we're going to use some framework for admin panel bc this may lead to versions conflicts
2. Styles should be cleaned, only some basic things need to be kept. Anyway all projects use their own styles for tags/pdf/ui.

**Comment by paranoicsan** [comment]
I think we can close this as we cleaned up a code to get rid of the remaining issue.
